bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_shopping_bag, name='view_shopping_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_shopping_bag,
         name='adjust_shopping_bag'),
    path('remove/<item_id>/', views.remove_from_shopping_bag,
         name='remove_from_shopping_bag'),
]

mani_and_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_info, name='product_info'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('manage_inventory/', views.manage_inventory,
         name='manage_inventory'),
    path('update_inventory/<int:product_id>/', views.update_inventory,
         name='update_inventory'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile

# Code from Boutique Ado


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


# Code from Boutique Ado
class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)        # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from django.http import HttpResponseRedirect
from django.http import JsonResponse

from django.forms.models import inlineformset_factory
from django.forms import modelformset_factory
from .models import Product, Category, Inventory
from .forms import (
    ProductImage, ProductForm, ProductImageFormSet,
    ProductImageForm, InventoryForm, InventoryUpdateForm
)

# Create your views here.


def all_products(request):
    """ View to show products, including filtering and queries -
    Code used from Boutique Ado """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    view = 'grid'  # Default view

    # Handle (Grid or List) view toggle
    if 'view' in request.GET:
        view = request.GET['view']

    if request.GET:
        # Handle sorting
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            elif sortkey == 'category':
                sortkey = 'category__name'
            elif sortkey == 'rating':
                sortkey = 'rating'

            # Handle direction
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        # Handle category filtering
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        # Handle search query
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter a search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query
                )
            products = products.filter(queries)

    # Determine current sorting state
    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'view': view,  # Pass the current view state to the template
    }

    return render(request, 'products/products.html', context)


def product_info(request, product_id):
    """ View to show product information and inventory
    - Code used from Boutique Ado (Adapted)"""

    product = get_object_or_404(Product, pk=product_id)
    images = product.images.all()

    context = {
        'product': product,
        'images': images,
    }

    return render(request, 'products/product_info.html', context)


@login_required
def add_product(request):
    """ Add a product to the store. """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)

        # Check if the product form is valid
        if product_form.is_valid():
            product = product_form.save(commit=False)  # Don't save yet

            # Save the product first (so we can associate images with it)
            product.save()

            # Now, handle additional images (image_2 and image_3)
            image_2 = product_form.cleaned_data.get('image_2')
            image_3 = product_form.cleaned_data.get('image_3')

            # Set image_2 and image_3 to the product instance if present
            if image_2:
                product.image_2 = image_2
            if image_3:
                product.image_3 = image_3

            # Save the product again with the additional images
            product.save()

            # Check if product has sizes
            if product.has_sizes:
                # Define the sizes (you can modify these as needed)
                sizes = ['S', 'M', 'L']  # Example sizes, modify as needed

                # Create inventory items for each size
                for size in sizes:
                    Inventory.objects.create(
                        product=product,
                        size=size,
                        quantity=1  # Default quantity
                    )
                messages.success(
                    request,
                    'Successfully added product with sizes and inventory!'
                    )
            else:
                messages.success(request, 'Successfully added product!')

            # Redirect to the products page or wherever you want
            return redirect('products')
        else:
            messages.error(request,
                           'Failed to add product. \
                            Please ensure the form is valid.'
                           )

    else:
        product_form = ProductForm()

    return render(request, 'products/add_product.html', {'form': product_form})


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()  # Save the product with any updates

            # Handle additional images if uploaded
            image_2 = form.cleaned_data.get('image_2')
            image_3 = form.cleaned_data.get('image_3')

            if image_2:
                product.image_2 = image_2
            if image_3:
                product.image_3 = image_3

            # Save the product again with the additional images
            product.save()

            messages.success(request, 'Product updated successfully!')
            return redirect(reverse('product_info', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update the product. Please check the form.'
                )

    else:
        form = ProductForm(instance=product)

    return render(
        request, 'products/edit_product.html',
        {'form': form, 'product': product}
        )


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def manage_inventory(request):
    """ Get all products and inventory information """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    products = Product.objects.prefetch_related('inventory').all()
    return render(
        request, 'products/manage_inventory.html',
        {'products': products}
        )


@login_required
def update_inventory(request, product_id):
    """ Allows users to update inventory stock for a product """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, id=product_id)
    inventory = Inventory.objects.filter(product=product)

    if request.method == 'POST':
        form = InventoryUpdateForm(request.POST, initial={'product': product})
        if form.is_valid():
            size = form.cleaned_data.get('size')
            quantity = form.cleaned_data.get('quantity')

            existing_inventory = Inventory.objects.filter(
                product=product, size=size
                ).first()

            if existing_inventory:
                # If size exists, check if the quantity is valid
                if quantity < 0:
                    messages.error(request, "Quantity cannot be negative.")
                else:
                    existing_inventory.quantity = quantity
                    existing_inventory.save()
                    messages.success(
                        request, f"Updated stock for size {size}."
                        )
            else:
                # Add new size only if it's not already there
                if quantity < 0:
                    messages.error(request, "Quantity cannot be negative.")
                else:
                    Inventory.objects.create(
                        product=product, size=size, quantity=quantity
                        )
                    messages.success(request, f"Added new size {size}.")

            return redirect('manage_inventory')
    else:
        # Pre-fill the form with the current inventory (size and quantity)
        inventory_item = inventory.first() if inventory.exists() else None
        form = InventoryUpdateForm(
            initial={
                'product': product,
                # Default to 'M' if no inventory exists
                'size': inventory_item.size if inventory_item else 'M',
                # Default to 1 if no inventory exists
                'quantity': inventory_item.quantity if inventory_item else 1,
            }
        )

    return render(

products/templates/products/add_product.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-2" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-2" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-2" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-2" type="submit">Update Product</button>
                </div>
            </form>
        </div>            
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_info.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<!-- Code used from Boutique Ado. 
 With some changes to image to display carousel. Added SKU-->
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <!-- Carousel Section -->
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div id="productCarousel" class="carousel slide my-5" data-ride="carousel">
                    <div class="carousel-inner">
                        <!-- Main Product Image -->
                        {% if product.image %}
                        <div class="carousel-item active">
                            <a href="{{ product.image.url }}" target="_blank">
                                <img src="{{ product.image.url }}" class="d-block w-100 img-fluid product-image" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% elif product.image_url %}
                        <div class="carousel-item active">
                            <a href="{{ product.image_url }}" target="_blank">
                                <img src="{{ product.image_url }}" class="d-block w-100 img-fluid product-image" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% else %}
                        <div class="carousel-item active">
                            <a href="{{ MEDIA_URL }}noimage.png" target="_blank">
                                <img src="{{ MEDIA_URL }}noimage.png" class="d-block w-100 img-fluid product-image" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% endif %}

                        <!-- Additional Images -->
                        {% if product.image_2 %}
                        <div class="carousel-item">
                            <a href="{{ product.image_2.url }}" target="_blank">
                                <img src="{{ product.image_2.url }}" class="d-block w-100 img-fluid product-image" alt="Additional image of {{ product.name }}">
                            </a>
                        </div>
                        {% endif %}
                        {% if product.image_3 %}
                        <div class="carousel-item">
                            <a href="{{ product.image_3.url }}" target="_blank">
                                <img src="{{ product.image_3.url }}" class="d-block w-100 img-fluid product-image" alt="Additional image of {{ product.name }}">
                            </a>
                        </div>
                        {% endif %}
                        
                        <!-- Related Product Images -->
                        {% for img in product.images.all %}
                        <div class="carousel-item">
                            <a href="{{ img.image.url }}" target="_blank">
                                <img src="{{ img.image.url }}" class="d-block w-100 img-fluid product-image" alt="Image of {{ product.name }}">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Carousel Controls -->
                    <a class="carousel-control-prev" href="#productCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#productCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <!-- Product Information -->
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0"><strong>{{ product.name }}</strong></p>
                    <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a href="{% url 'products' %}?category={{ product.category.friendly_name }}" class="text-muted">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}

                    {% if product.sku %}
                    <p class="text-muted"><i class="fas fa-barcode"></i> {{ product.sku }}</small>
                    {% else %}
                    <small class="text-muted">No SKU</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>

                    <!-- Stock Information -->
                    {% if product.has_sizes %}
                    <h4>Sizes and Stock</h4>
                    <ul>
                        {% for inventory in product.inventory.all %}
                        <li>
                            <strong>Size:</strong> {{ inventory.size }} | <strong>Stock:</strong> {{ inventory.quantity }}
                            {% if inventory.quantity == 0 %}
                            <span class="text-danger">Out of Stock</span>
                            {% elif inventory.quantity <= 5 %}
                            <span class="text-warning">Low Stock ({{ inventory.quantity }} left)</span>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>Stock: {{ product.inventory.first.quantity }}</p>
                    {% if product.inventory.first.quantity == 0 %}
                        <span class="text-danger">Out of Stock</span>
                    {% elif product.inventory.first.quantity <= 5 %}
                        <span class="text-warning">Low Stock ({{ product.inventory.first.quantity }} left)</span>
                    {% endif %}
                    {% endif %}

                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with product.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                        {% for inventory in product.inventory.all %}
                                            <option value="{{ inventory.size }}">{{ inventory.size }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group input-group-{{ product.id }}">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0 decrement-qty_{{ product.id }}" 
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0 increment-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                                    <!-- Wishlist Button next to Quantity input -->
                                    {% if user.is_authenticated %}
                                        {% if product not in request.user.wishlist.all %}
                                            <a href="{% url 'add_to_wishlist' product.id %}" class="btn btn-sm ml-3">
                                                <i class="fas fa-heart fa-lg"></i>  <!-- Larger heart icon -->
                                            </a>
                                        {% else %}
                                            <p>Please <a href="{% url 'login' %}">login</a> to add to your wishlist.</p>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>

                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-2 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-2 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/update_inventory.html
{% extends "base.html" %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Update Inventory for {{ product.name }}</h2>
            <hr>
        </div>
    </div>
    
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="text-center">
            <a class="btn btn-outline-black rounded-2" href="{% url 'products' %}">Cancel</a>
            <button class="btn btn-black rounded-2" type="submit">Update Product</button>
        </div>
    </form>
</div>
{% endblock %}